"""description of changes

Revision ID: 3aec27e0a9ef
Revises: 27ee41858d24
Create Date: 2026-05-02 18:50:30.024524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aec27e0a9ef'
down_revision: Union[str, Sequence[str], None] = '27ee41858d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # fixed
    op.add_column('users', sa.Column('is_profile_complete', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'is_profile_complete')
    # ### end Alembic commands ###
